import Head from "next/head";
import { VPC_DIAGRAM } from "./diagrams/vpc.diagram";
import styles from "../styles/Home.module.css";

const VPC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.grid}>
          <h1>VPC</h1>
          <p>
            VPC is a virtual private cloud (VPC). It is a virtual network that
            is isolated from the Internet and other networks. And can be thought
            of as your cloud-based data center where all your servers,
            databases, and applications are hosted.
          </p>
          <VPC_DIAGRAM />
          <span className={styles.card}>
            <h2>CIDR</h2>
            <p>
              CIDR is a notation for specifying an IP address range. It is a
              string of the form x.x.x.x/y, where x.x.x.x is the base address
              and y is the number of bits in the network mask.
            </p>
          </span>
          <span className={styles.card}>
            <h2>AWS Region</h2>
            <p>
              AWS Region is a geographical area where AWS services are provided.
            </p>
          </span>
          <span className={styles.card}>
            <h2>AWS Availability Zone</h2>
            <p>
              There are multiple Availability zones per region in AWS. This is
              to ensure resilience of your application.
            </p>
          </span>
          <span className={styles.card}>
            <h2>AWS Subnets</h2>
            <p>
              Within the VPC network, you can create subnets. Subnets are
              isolated networks that can be used to isolate your application.
            </p>

            <h2>Public Subnet</h2>
            <p>
              A public subnet is a subnet that is connected to the Internet. It
              is used to connect your application to the Internet.
            </p>
            <h2>Private Subnet</h2>
            <p>
              A private subnet is a subnet that is not connected to the
              Internet.
            </p>
          </span>
        </div>
      </main>
    </div>
  );
};

export default VPC;
