import Image from "next/image";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const PrivateConnection = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>EC2 | Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ maxWidth: "800px" }}>
          <h1>Role based access with IAM</h1>
          <img src="/diagrams/nat-ref-arch.png" alt="nat types" width="800px" />
          <ol>
            <li>Create two subnets, one public and one private</li>
            <li>
              Create two EC2 instances, one associated with the public subnet,
              and the other with private subnet.
            </li>
            <li>
              Create a NAT GW, choose all the defaults and assign an Elastic IP
              to it.
            </li>
            <li>
              Create a new route table on the VPC and call it "Private Route
              Table"
            </li>
            <li>
              The ROute table should already have one route, connecting local
              traffic the subnet.
            </li>
            <li>
              Lets add a new route to the provate RT that takes local inbound
              traffic as the source and sets all outbound 0.0.0.0/0 traffic to
              the NAT GW.
            </li>
            <li>
              Click "Add Route". For the destination select 0.0.0.0/0 and select
              the NAT gateway we created from the dropdown in the "target"
              field.
            </li>
          </ol>
          <img
            src="/diagrams/private-route-table.png"
            alt="private RT"
            width={800}
          />
        </div>
      </main>
    </div>
  );
};

export default PrivateConnection;
