import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const VPC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Build on AWS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.grid}>
          <h1>NAT: Network Address Translation</h1>
          The NAT gateway is a one-way door to the internet. Services in private
          subnets can use the NAT gateway to access the internet. The internet
          cannot access services in private subnets through the NAT gateway
        </div>
      </main>
    </div>
  );
};

export default VPC;
