import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Private = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Build on AWS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.grid}>
          <span>
            <h1>Private</h1>
            steps:
            <ol>
              <li>Create a new AWS account</li>
              <li>Create a VPC</li>
              <li>Create a public subnet</li>
              <li>Create a private subnet</li>
              <li>Create a public route table</li>
              <li>Create a private route table</li>
              <li>Create a public security group</li>
              <li>Create a private security group</li>
              <li>Create a public internet gateway</li>
              <li>Create a NAT gateway in Public subnet</li>
              <li>Configure route table to allow traffic from NAT</li>
            </ol>
          </span>
          <span>
            <Link href="https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html">
              Docs
            </Link>
          </span>
        </div>
      </main>
    </div>
  );
};

export default Private;
